export const UNIVERSAL_CORE_COPY = {
  it: {
    editorStep: 'TYPE CONSTRUCTION LAB / PASSO 10',
    typeSystem: 'SISTEMA TIPOGRAFICO',
    selectGlyph: 'Seleziona glifo',
    reset: 'RESET',
    tools: 'STRUMENTI',
    toolSelect: 'Seleziona',
    toolBowl: 'Occhio',
    toolStem: 'Asta',
    toolBar: 'Barra',
    view: 'VISTA',
    design: 'DISEGNO',
    construction: 'COSTRUZIONE',
    system: 'SISTEMA',
    test: 'TEST',
    glyph: 'GLIFO',
    selected: 'SELEZIONATO',
    crossbar: 'BARRA',
    position: 'POSIZIONE',
    inset: 'RIENTRO',
    centerCrossbar: 'CENTRA BARRA',
    openBowl: 'OCCHIO APERTO',
    aperture: 'APERTURA',
    bowl: 'OCCHIO',
    width: 'LARGHEZZA',
    height: 'ALTEZZA',
    fitXHeightBaseline: 'ADATTA X-HEIGHT ↔ BASELINE',
    snapTangentStem: 'ALLINEA TANGENTE ALL’ASTA',
    editCrossbar: 'MODIFICA BARRA',
    stem: 'ASTA',
    descender: 'DISCENDENTE',
    ascender: 'ASCENDENTE',
    anchorAscender: 'ANCORA ASCENDENTE',
    joinTangentBowl: 'UNISCI TANGENTE ALL’OCCHIO',
    familyRules: 'REGOLE DI FAMIGLIA',
    stroke: 'SPESSORE',
    overshoot: 'OVERSHOOT',
    outerBowl: 'OCCHIO ESTERNO',
    spacingMetrics: 'SPAZIATURA / METRICHE',
    spacingGlyph: 'Glifo di spaziatura',
    leftSideBearing: 'MARGINE SINISTRO',
    rightSideBearing: 'MARGINE DESTRO',
    visualWidth: 'LARGHEZZA VISIVA',
    advanceWidth: 'LARGHEZZA DI AVANZAMENTO',
    kerningPairs: 'KERNING / COPPIE',
    kerningPair: 'Coppia di kerning',
    pairValue: 'VALORE COPPIA',
    pair: 'COPPIA',
    leftAdvance: 'AVANZAMENTO SINISTRO',
    rightAdvance: 'AVANZAMENTO DESTRO',
    kern: 'KERN',
    typeTest: 'TEST TIPOGRAFICO',
    useSystem: 'USA IL SISTEMA',
    builtGlyphs: 'GLIFI COSTRUITI',
    text: 'TESTO',
    size: 'DIMENSIONE',
    tracking: 'TRACKING',
    typeTestText: 'Testo di prova tipografica',
    fallbackGlyph: 'Glifo non ancora costruito',
    builtInstances: 'ISTANZE COSTRUITE',
    missingGlyphs: 'GLIFI MANCANTI',
    coverage: 'COPERTURA',
    glyphs: 'GLIFI',
    liveSpecimen: 'SPECIMEN DAL VIVO',
    sharedSystemSeven: 'SISTEMA CONDIVISO / SETTE GLIFI',
    linked: 'COLLEGATI',
    customGlyph: 'Glifo',
    systemView: 'VISTA DI SISTEMA',
    oneBowlSeven: 'UN OCCHIO / SETTE GLIFI',
    systemStatus: 'SPECCHIO + VERTICALE + OCCHIO APERTO',
    rule: 'REGOLA',
    status: 'STATO',
    shared: 'CONDIVISO',
    derived: 'DERIVATO',
    structural: 'STRUTTURALE',
    stemSide: 'LATO ASTA',
    left: 'SINISTRA',
    right: 'DESTRA',
    verticalRange: 'INTERVALLO VERTICALE',
    only: 'SOLO',
    advance: 'AVANZAMENTO',
    glyphMetric: 'METRICA GLIFO',
    pairs: 'COPPIE',
    structure: {
      bowl: 'OCCHIO',
      openBowl: 'OCCHIO APERTO',
      openBowlBar: 'OCCHIO APERTO + BARRA',
      ascenderLeft: 'ASCENDENTE ← OCCHIO',
      ascenderRight: 'OCCHIO → ASCENDENTE',
      descenderLeft: 'DISCENDENTE ← OCCHIO',
      descenderRight: 'OCCHIO → DISCENDENTE',
    },
    sharedDna: 'DNA CONDIVISO',
    liveFamily: 'FAMIGLIA ATTIVA',
    mirrored: 'SPECCHIATO',
    specific: 'SPECIFICO',
    verticalSystem: 'SISTEMA VERTICALE',
    axes: 'ASSI',
    spacing: 'SPAZIATURA',
    perGlyph: 'PER GLIFO',
    metricSets: 'SET METRICI',
  },
  de: {
    editorStep: 'TYPE CONSTRUCTION LAB / SCHRITT 10',
    typeSystem: 'SCHRIFTSYSTEM',
    selectGlyph: 'Glyphe wählen',
    reset: 'RESET',
    tools: 'WERKZEUGE',
    toolSelect: 'Auswahl',
    toolBowl: 'Rundung',
    toolStem: 'Stamm',
    toolBar: 'Querstrich',
    view: 'ANSICHT',
    design: 'ENTWURF',
    construction: 'KONSTRUKTION',
    system: 'SYSTEM',
    test: 'TEST',
    glyph: 'GLYPHE',
    selected: 'AUSGEWÄHLT',
    crossbar: 'QUERSTRICH',
    position: 'POSITION',
    inset: 'EINZUG',
    centerCrossbar: 'QUERSTRICH ZENTRIEREN',
    openBowl: 'OFFENE RUNDUNG',
    aperture: 'ÖFFNUNG',
    bowl: 'RUNDUNG',
    width: 'BREITE',
    height: 'HÖHE',
    fitXHeightBaseline: 'AN X-HÖHE ↔ GRUNDLINIE ANPASSEN',
    snapTangentStem: 'TANGENTE AM STAMM AUSRICHTEN',
    editCrossbar: 'QUERSTRICH BEARBEITEN',
    stem: 'STAMM',
    descender: 'UNTERLÄNGE',
    ascender: 'OBERLÄNGE',
    anchorAscender: 'OBERLÄNGE VERANKERN',
    joinTangentBowl: 'TANGENTE AN RUNDUNG ANSCHLIESSEN',
    familyRules: 'FAMILIENREGELN',
    stroke: 'STRICHSTÄRKE',
    overshoot: 'OVERSHOOT',
    outerBowl: 'ÄUSSERE RUNDUNG',
    spacingMetrics: 'SPACING / METRIKEN',
    spacingGlyph: 'Spacing-Glyphe',
    leftSideBearing: 'LINKE VORBREITE',
    rightSideBearing: 'RECHTE VORBREITE',
    visualWidth: 'VISUELLE BREITE',
    advanceWidth: 'ZEICHENBREITE',
    kerningPairs: 'KERNING / PAARE',
    kerningPair: 'Kerning-Paar',
    pairValue: 'PAARWERT',
    pair: 'PAAR',
    leftAdvance: 'LINKE ZEICHENBREITE',
    rightAdvance: 'RECHTE ZEICHENBREITE',
    kern: 'KERN',
    typeTest: 'SCHRIFTTEST',
    useSystem: 'SYSTEM TESTEN',
    builtGlyphs: 'GEBAUTE GLYPHEN',
    text: 'TEXT',
    size: 'GRÖSSE',
    tracking: 'LAUFWEITE',
    typeTestText: 'Schrifttesttext',
    fallbackGlyph: 'Glyphe noch nicht gebaut',
    builtInstances: 'GEBAUTE INSTANZEN',
    missingGlyphs: 'FEHLENDE GLYPHEN',
    coverage: 'ABDECKUNG',
    glyphs: 'GLYPHEN',
    liveSpecimen: 'LIVE-SPECIMEN',
    sharedSystemSeven: 'GEMEINSAMES SYSTEM / SIEBEN GLYPHEN',
    linked: 'VERKNÜPFT',
    customGlyph: 'Glyphe',
    systemView: 'SYSTEMANSICHT',
    oneBowlSeven: 'EINE RUNDUNG / SIEBEN GLYPHEN',
    systemStatus: 'SPIEGEL + VERTIKAL + OFFENE RUNDUNG',
    rule: 'REGEL',
    status: 'STATUS',
    shared: 'GEMEINSAM',
    derived: 'ABGELEITET',
    structural: 'STRUKTURELL',
    stemSide: 'STAMMSEITE',
    left: 'LINKS',
    right: 'RECHTS',
    verticalRange: 'VERTIKALBEREICH',
    only: 'NUR',
    advance: 'ZEICHENBREITE',
    glyphMetric: 'GLYPHENMETRIK',
    pairs: 'PAARE',
    structure: {
      bowl: 'RUNDUNG',
      openBowl: 'OFFENE RUNDUNG',
      openBowlBar: 'OFFENE RUNDUNG + QUERSTRICH',
      ascenderLeft: 'OBERLÄNGE ← RUNDUNG',
      ascenderRight: 'RUNDUNG → OBERLÄNGE',
      descenderLeft: 'UNTERLÄNGE ← RUNDUNG',
      descenderRight: 'RUNDUNG → UNTERLÄNGE',
    },
    sharedDna: 'GEMEINSAME DNA',
    liveFamily: 'LIVE-FAMILIE',
    mirrored: 'GESPIEGELT',
    specific: 'SPEZIFISCH',
    verticalSystem: 'VERTIKALSYSTEM',
    axes: 'ACHSEN',
    spacing: 'SPACING',
    perGlyph: 'PRO GLYPHE',
    metricSets: 'METRIKSÄTZE',
  },
  en: {
    editorStep: 'TYPE CONSTRUCTION LAB / STEP 10',
    typeSystem: 'TYPE SYSTEM',
    selectGlyph: 'Select glyph',
    reset: 'RESET',
    tools: 'TOOLS',
    toolSelect: 'Select',
    toolBowl: 'Bowl',
    toolStem: 'Stem',
    toolBar: 'Bar',
    view: 'VIEW',
    design: 'DESIGN',
    construction: 'CONSTRUCTION',
    system: 'SYSTEM',
    test: 'TEST',
    glyph: 'GLYPH',
    selected: 'SELECTED',
    crossbar: 'CROSSBAR',
    position: 'POSITION',
    inset: 'INSET',
    centerCrossbar: 'CENTER CROSSBAR',
    openBowl: 'OPEN BOWL',
    aperture: 'APERTURE',
    bowl: 'BOWL',
    width: 'WIDTH',
    height: 'HEIGHT',
    fitXHeightBaseline: 'FIT X-HEIGHT ↔ BASELINE',
    snapTangentStem: 'SNAP TANGENT TO STEM',
    editCrossbar: 'EDIT CROSSBAR',
    stem: 'STEM',
    descender: 'DESCENDER',
    ascender: 'ASCENDER',
    anchorAscender: 'ANCHOR ASCENDER',
    joinTangentBowl: 'JOIN TANGENT TO BOWL',
    familyRules: 'FAMILY RULES',
    stroke: 'STROKE',
    overshoot: 'OVERSHOOT',
    outerBowl: 'OUTER BOWL',
    spacingMetrics: 'SPACING / METRICS',
    spacingGlyph: 'Spacing glyph',
    leftSideBearing: 'LEFT SIDE BEARING',
    rightSideBearing: 'RIGHT SIDE BEARING',
    visualWidth: 'VISUAL WIDTH',
    advanceWidth: 'ADVANCE WIDTH',
    kerningPairs: 'KERNING / PAIRS',
    kerningPair: 'Kerning pair',
    pairValue: 'PAIR VALUE',
    pair: 'PAIR',
    leftAdvance: 'LEFT ADVANCE',
    rightAdvance: 'RIGHT ADVANCE',
    kern: 'KERN',
    typeTest: 'TYPE TEST',
    useSystem: 'USE THE SYSTEM',
    builtGlyphs: 'BUILT GLYPHS',
    text: 'TEXT',
    size: 'SIZE',
    tracking: 'TRACKING',
    typeTestText: 'Type test text',
    fallbackGlyph: 'Fallback glyph — not built yet',
    builtInstances: 'BUILT INSTANCES',
    missingGlyphs: 'MISSING GLYPHS',
    coverage: 'COVERAGE',
    glyphs: 'GLYPHS',
    liveSpecimen: 'LIVE SPECIMEN',
    sharedSystemSeven: 'SHARED SYSTEM / SEVEN GLYPHS',
    linked: 'LINKED',
    customGlyph: 'Custom glyph',
    systemView: 'SYSTEM VIEW',
    oneBowlSeven: 'ONE BOWL / SEVEN GLYPHS',
    systemStatus: 'MIRROR + VERTICAL + OPEN-BOWL SYSTEM',
    rule: 'RULE',
    status: 'STATUS',
    shared: 'SHARED',
    derived: 'DERIVED',
    structural: 'STRUCTURAL',
    stemSide: 'STEM SIDE',
    left: 'LEFT',
    right: 'RIGHT',
    verticalRange: 'VERTICAL RANGE',
    only: 'ONLY',
    advance: 'ADVANCE',
    glyphMetric: 'GLYPH METRIC',
    pairs: 'PAIRS',
    structure: {
      bowl: 'BOWL',
      openBowl: 'OPEN BOWL',
      openBowlBar: 'OPEN BOWL + BAR',
      ascenderLeft: 'ASCENDER ← BOWL',
      ascenderRight: 'BOWL → ASCENDER',
      descenderLeft: 'DESCENDER ← BOWL',
      descenderRight: 'BOWL → DESCENDER',
    },
    sharedDna: 'SHARED DNA',
    liveFamily: 'LIVE FAMILY',
    mirrored: 'MIRRORED',
    specific: 'SPECIFIC',
    verticalSystem: 'VERTICAL SYSTEM',
    axes: 'AXES',
    spacing: 'SPACING',
    perGlyph: 'PER GLYPH',
    metricSets: 'METRIC SETS',
  },
};
